"""add caption to document_images

Revision ID: 4bc22aeafa69
Revises: 97b028aa803e
Create Date: 2026-07-14 18:57:41.249689

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc22aeafa69'
down_revision: str | None = '97b028aa803e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_images', sa.Column('caption', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_images', 'caption')
    # ### end Alembic commands ###
