"""add message position and citations

Revision ID: e2c808ac9835
Revises: fa036529f91f
Create Date: 2026-07-21 23:59:33.811419

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c808ac9835'
down_revision: str | None = 'fa036529f91f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('position', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('citations', sa.JSON(), nullable=True))
    op.create_unique_constraint(op.f('uq_messages_conversation_id'), 'messages', ['conversation_id', 'position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_messages_conversation_id'), 'messages', type_='unique')
    op.drop_column('messages', 'citations')
    op.drop_column('messages', 'position')
    # ### end Alembic commands ###
